### PR TITLE
Ability to set the height and width of a view dependent on views that are not the parent

### PR DESCRIPTION
**Pull request by appbureauet**
This pull request tries to fix issue #3 
It is still a little rough around the edges, you manually need to add views in the correct order for this to work (like you do with native relative layout methods)

### CODE REVIEW

**Comment by appbureauet** [comment]
I still need to add code for dependent views finding the dependent views - I plan to add this tonight.

-- update: now added

**Comment by appbureauet** [comment]
Just realised I am collecting dependent views wrongly, I will do another commit later tonight 😊

-- update: now added

**Comment by lprichar** [comment]
Haven't forgotten this @appbureauet, sorry for the delay, I was on holiday.  Will be getting back to it very shortly.

**Review by lprichar — CHANGES_REQUESTED** [review]
Ok, I see what you're doing here and it is *so* cool.  This is impressive in scope, and how it pretty much overcomes most of XF's RelativeLayout issues.

I have two big concerns:

The first problem I have is performance.  Try clicking on the "EasyLayout.Forms Performance".  At least in iOS it now takes a second to load.  Then, if you start scrolling you can feel the sluggishness, even in a simulator.  As cool as GetDependentViews() is, I suspect the problem may start there.  Maybe we could short-circuit the recursion.

The second problem I have is it appears to break existing functionality.  Check out "Layout Example".  There are a couple of render errors.  For one thing _left and _right no longer honor the Bottom() constraint, instead they're pushed all the way to the bottom of the screen.  For another thing the Right() constraint is no longer working for the _top and _bottom views.

If we can solve those two problems this is ready to go.  I'm sorry for the long delay in getting back to you, you clearly put a lot of time and energy into this extremely impressive solution and I hope we can get it merged back in.

**Comment by mellson** [comment]
Thank you for your constructive inputs @lprichar 👍
I have tried to address both your concerns in the commit above.

Ha ha - just realised I wrote this from my other GitHub account 😊

**Comment by appbureauet** [comment]
I have moved my fork to my private account @mellson - so if we are to proceed with this at some point - I will be @mellson from now on 😄

**Review by lprichar — APPROVED** [review]
Works beautifully!  No UI regressions, works fast, and supports way more sophisticated layouts than the built in RelativeLayout could.  Nicely done!  Sorry for the long delays.

**Pull request merged**
